### ISSUE TITLE
Warning: the origin domain used now serves malware

### ISSUE THREAD

**Issue by mevanloon** [UniqueLogic/onlyfans-downloader#1]
The original domain used (onlyfansdownloader.co) now redirects to anyloader, which contains obfuscated malware. It tries to get you to update to code that's not on Github, so please be advised that you shouldn't.

**Comment by horomanero** [comment]
@mevanloon hello, I downloaded this extension from
https://github.com/UniqueLogic/onlyfans-downloader/releases/tag/v1.0
and I have just tried to use it for 15 minutes. Do you think I have been infected? I use Fedora as operating system and I opened Chrome just to use this extension, since I use Firefox during everyday usage

**Comment by UniqueLogic** [comment]
It is not malware. [Anyloader](https://anyloader.com) is our new website,  The code was always kept obfuscated to protect it from people copying our latest updates.

**Comment by mevanloon** [comment]
Then why even have a GitHub page? What you're saying is not congruent with what you're doing; there is no monetisation model, so why protect *front-end* facing code, especially when you're also requiring a server on a separate domain?

If this was an honest project, the source code on the GitHub would match the extension served from that domain, so we can be sure that there's no malware served. That's way more important than 'copy protection' -- also, protection from *whom*? If somebody really wanted to copy it, they can just run it through a de-obfuscator; obfuscation famously does not protect against copying. The only real reason to obfuscate the extension's JS code is to serve malware.
